apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: workers
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      #machine.openshift.io/cluster-api-machineset: cluster-49bb-wkbwx-ocs-us-east-2a
  unhealthyConditions:
  - type: Ready
    timeout: 300s
    status: "False"
  - type: Ready
    timeout: 300s
    status: Unknown
  maxUnhealthy: 40%
  nodeStartupTimeout: 10m
