apiVersion: v1
kind: Service
metadata:
  labels:
    # This label is required in order for the ServiceMonitor to match this Service.
    app: prometheus-example-app
  name: prometheus-example-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: prometheus-example-app
  type: ClusterIP
